### ISSUE TITLE
Can't use Psearch on the Merginal buffer

### ISSUE THREAD

**Issue by idanarye** [idanarye/vim-merginal#10]
```
Error detected while processing function psearch#Open:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/idanarye/.vim/bundle/psearch.vim/autoload/psearch.py", line 296, in open
    self.update_launcher()
  File "/home/idanarye/.vim/bundle/psearch.vim/autoload/psearch.py", line 207, in update_launcher
    self.search(self.input_so_far)
  File "/home/idanarye/.vim/bundle/psearch.vim/autoload/psearch.py", line 149, in search
    vim.command("b {0}".format(self.curr_buf.number))
vim.error: attempt to refer to deleted buffer
```

**Comment by idanarye** [comment]
Note to self: I'm using my own fork of Psearch, since the original was removed from GitHub

**Comment by idanarye** [comment]
Psearch is a dead project, and has better alternatives now. Not going to do this.
